pluginName = 1C:Enterprise Development Tools Profiling UI
providerName = 1C-Soft LLC

view.profiling.name = Performance Meter
command.profiling.name = Performance Meter
ruler.profiling.name = Performance Results
ruler.command.showOutdatedResults = Show Outdated Results
ruler.command.showRuler = Show Results Ruler

component.profiling.label = 1C:EDT Performance Meter

wizard.import.name=Performance Measurements
wizard.import.description=Import performance measurements from files.
wizard.export.name=Performance Measurements
wizard.export.description=Export performance measurements to files.

view.profiling.compare.name = Comparing performance results
