aboutText=1C:Link for 1C:EDT\n\
Provide access to your developed 1C applications via the Internet.\n\
\n\
Version: {featureVersion}\n\
Release date: {0}\n\
\n\
For more information please see http://1c.link