package com.e1c.edt.ai.tools;

import com.e1c.edt.ai.ICancellationProgressMonitor;
import com.e1c.edt.ai.IMarkdownUtils;
import com.e1c.edt.ai.IMarkersProvider;
import com.e1c.edt.ai.IMcpTool;
import com.e1c.edt.ai.IMcpTools;
import com.e1c.edt.ai.IMcpToolsCallMessageFactory;
import com.e1c.edt.ai.MarkdownUtils;
import com.e1c.edt.ai.McpTools;
import com.google.inject.AbstractModule;
import com.google.inject.Singleton;
import com.google.inject.multibindings.Multibinder;

public class MCPToolsModule extends AbstractModule {
   protected void configure() {
      this.bind(IMcpTools.class).to(McpTools.class).in(Singleton.class);
      Multibinder<IMcpTool> toolBinder = Multibinder.newSetBinder(this.binder(), IMcpTool.class);
      toolBinder.addBinding().to(ExecuteMcpTool.class);
      toolBinder.addBinding().to(GitMcpTool.class);
      toolBinder.addBinding().to(GetProjectsMcpTool.class);
      toolBinder.addBinding().to(GetCommandCategoriesMcpTool.class);
      toolBinder.addBinding().to(GetCommandsMcpTool.class);
      toolBinder.addBinding().to(ExecuteCommandMcpTool.class);
      toolBinder.addBinding().to(ReadMcpTool.class);
      toolBinder.addBinding().to(FindMcpTool.class);
      toolBinder.addBinding().to(SearchTextMcpTool.class);
      toolBinder.addBinding().to(SearchFilesMcpTool.class);
      toolBinder.addBinding().to(GlobMcpTool.class);
      toolBinder.addBinding().to(ListMcpTool.class);
      toolBinder.addBinding().to(GitCommitsMcpTool.class);
      toolBinder.addBinding().to(GitDiffMcpTool.class);
      toolBinder.addBinding().to(LocalHistoryMcpTool.class);
      toolBinder.addBinding().to(LocalChangesMcpTool.class);
      toolBinder.addBinding().to(NavigationHistoryMcpTool.class);
      toolBinder.addBinding().to(WriteMcpTool.class);
      toolBinder.addBinding().to(EditMcpTool.class);
      toolBinder.addBinding().to(DeleteMcpTool.class);
      toolBinder.addBinding().to(GetMarkersMcpTool.class);
      toolBinder.addBinding().to(SetMarkersMcpTool.class);
      toolBinder.addBinding().to(DeleteMarkersMcpTool.class);
      toolBinder.addBinding().to(JShellSessionMcpTool.class);
      toolBinder.addBinding().to(JShellMcpTool.class);
      this.bind(IProcessRunner.class).to(ProcessRunner.class).in(Singleton.class);
      this.bind(ICancellationProgressMonitor.class).to(CancellationProgressMonitor.class);
      this.bind(IBuildWaiter.class).to(BuildWaiter.class).in(Singleton.class);
      this.bind(IMcpToolsCallMessageFactory.class).to(McpToolsCallMessageFactory.class).in(Singleton.class);
      this.bind(IMarkdownUtils.class).to(MarkdownUtils.class).in(Singleton.class);
      this.bind(ILocalHistoryUtils.class).to(LocalHistoryUtils.class).in(Singleton.class);
      this.bind(IPatternMatcher.class).to(PatternMatcher.class).in(Singleton.class);
      this.bind(IJShellSessionManager.class).to(JShellSessionManager.class).in(Singleton.class);
      this.bind(ITreeBuilder.class).to(TreeBuilder.class);
      this.bind(IJShellClassPathProvider.class).to(JShellClassPathProvider.class).in(Singleton.class);
      this.bind(IJShellClassPathProvider.class).to(JShellClassPathProvider.class).in(Singleton.class);
      this.bind(IRestrictedTypesProvider.class).to(RestrictedTypesProvider.class).in(Singleton.class);
      this.bind(IRestrictedTypesValidator.class).to(RestrictedTypesValidator.class).in(Singleton.class);
      this.bind(IReplacements.class).to(Replacements.class).in(Singleton.class);
      this.bind(IContentReplacer.class).to(ContentReplacer.class).in(Singleton.class);
      Multibinder<IReplacementStrategy> replacementStrategyBinder = Multibinder.newSetBinder(this.binder(), IReplacementStrategy.class);
      replacementStrategyBinder.addBinding().to(SimpleReplacer.class);
      replacementStrategyBinder.addBinding().to(LineTrimmedReplacer.class);
      replacementStrategyBinder.addBinding().to(BlockAnchorReplacer.class);
      replacementStrategyBinder.addBinding().to(WhitespaceNormalizedReplacer.class);
      replacementStrategyBinder.addBinding().to(IndentationFlexibleReplacer.class);
      replacementStrategyBinder.addBinding().to(EscapeNormalizedReplacer.class);
      replacementStrategyBinder.addBinding().to(TrimmedBoundaryReplacer.class);
      replacementStrategyBinder.addBinding().to(ContextAwareReplacer.class);
      replacementStrategyBinder.addBinding().to(MultiOccurrenceReplacer.class);
      Multibinder<IMarkersProvider> markersProviderBinder = Multibinder.newSetBinder(this.binder(), IMarkersProvider.class);
      markersProviderBinder.addBinding().to(CommonMarkersProvider.class);
      Multibinder<IJShellBindingProvider> jshellBindingProviderBinder = Multibinder.newSetBinder(this.binder(), IJShellBindingProvider.class);
      jshellBindingProviderBinder.addBinding().to(EclipsePlatformBindingProvider.class);
   }
}
