pluginName = 1C:Workmate
providerName = 1C-Soft LLC
traceName = 1C:Workmate

category.name = 1C:Workmate
view.name = 1C:Workmate

computer.name = Ask the 1C:Workmate
command.name.suggest = Suggest code
command.label.suggest = Suggest code
command.name.accept = Accept code
command.label.accept = Accept code
command.name.acceptpart = Accept part of code
command.label.acceptpart = Accept part of code
command.name.acceptline = Accept a line of code
command.label.acceptline = Accept a line of code
command.name.rollbackpart = Rollback part of code
command.label.rollbackpart = Rollback part of code
command.name.stop = Stop code completion
command.label.stop = Stop code completion
command.name.explain = Explain
command.label.explain = Explain
command.name.critic = Review
command.label.critic = Review
command.name.fixcode = Fix
command.label.fixcode = Fix
command.name.generatedoccomments = Generate doc comments for method
command.label.generatedoccomments = Generate doc comments for method
command.name.addcode = Add code
command.label.addcode = Add code
command.name.addfile = Add file
command.label.addfile = Add files...
command.name.feedback = Feedback
command.label.feedback = Feedback
command.name.statusbar = 1C:Workmate info
command.label.addfilestochat = Add files to chat with 1C:Workmate...

menu.label = 1C:Workmate

page.name = 1C:Workmate

command.tooltip.explain = Explain highlighted code
command.tooltip.critic = Review highlighted code
command.tooltip.fixcode = Fix highlighted code
command.tooltip.generatedoccomments = Generate doc comments for current method
command.tooltip.addcode = Add code fragment to the chat with 1C:Workmate
command.tooltip.addfile = Add files to the chat with 1C:Workmate
command.tooltip.feedback = Create feedback for 1C:Workmate
command.name.openChatView = Open chat with 1C:Workmate
